<a href="https://colab.research.google.com/github/obabakir/Nutri-React/blob/master/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [40]:
mydataset = {
  'cars': ["BMW", "Volvo", "Tesla", "Ford", "Ferrari", "Ford", "BMW"],
  'counts': [3, 7, 2, 6, 8, 5, 9]
}
# print("testing mydataset:", mydataset)
# print('===== =======')


df = pd.DataFrame(mydataset)
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2    Tesla       2
3     Ford       6
4  Ferrari       8
5     Ford       5
6      BMW       9

In [5]:
print(pd.__version__)

2.2.3

In [11]:
df.head(3)
# top => bottom
# bydefault 5 rows// -1 hide last element, 1 = index 0, 3 until = index 2 // 0 =  cars  counts

    cars  counts
0    BMW       3
1  Volvo       7
2  Twsla       2

In [46]:
df.tail(100)
# bottom => top
# opposite of head

      cars  counts
0      BMW       3
1    Volvo       7
2    Tesla       2
3     Ford       6
4  Ferrari       8
5     Ford       5
6      BMW       9

In [14]:
df.shape

(7, 2)

In [15]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [16]:
df.dtypes

cars      object
counts     int64
dtype: object

In [45]:
print('df:', df)

df:       cars  counts
0      BMW       3
1    Volvo       7
2    Tesla       2
3     Ford       6
4  Ferrari       8
5     Ford       5
6      BMW       9

In [19]:
df.describe()
# numerical columns only

         counts
count  7.000000
mean   5.714286
std    2.563480
min    2.000000
25%    4.000000
50%    6.000000
75%    7.500000
max    9.000000

In [44]:
df.iloc[2]
# selec specific one

cars      Tesla
counts        2
Name: 2, dtype: object

In [43]:
df.iloc[-1]
# select last

cars      BMW
counts      9
Name: 6, dtype: object

In [42]:
df.iloc[1:4]
# select: from 1 to 4

    cars  counts
1  Volvo       7
2  Tesla       2
3   Ford       6

In [41]:
df.iloc[2:4]
# from second index to fourth

    cars  counts
2  Tesla       2
3   Ford       6

In [ ]:
# <======>
# df.loc[:, ""] => columdagi malumotni olish un ishlatamiz
# <=====>

In [ ]:
df.loc[3, "cars"]
# result => Ford

In [29]:
df.loc[2:5, "cars"]
# <======>
# df.loc[:, ""]
# <=====>
# df.loc[3, "cars"] result => Ford

2      Twsla
3       Ford
4    Ferrari
5       Ford
Name: cars, dtype: object

In [47]:
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2    Tesla       2
3     Ford       6
4  Ferrari       8
5     Ford       5
6      BMW       9

In [30]:
# conditionals:
# ==, >=, <=, !=, >, <,

In [48]:
df[df["counts"] > 3]
# here 1- df === pd.DataFrame
# 2- df variable

      cars  counts
1    Volvo       7
3     Ford       6
4  Ferrari       8
5     Ford       5
6      BMW       9

In [49]:
df["counts"] != 3

0    False
1     True
2     True
3     True
4     True
5     True
6     True
Name: counts, dtype: bool

In [50]:
df[df["cars"] == "Tesla"]

    cars  counts
2  Tesla       2

In [57]:
# df.mean(numeric_only=True)
df["counts"].mean()

np.float64(5.714285714285714)

In [53]:
df.sum()
# columns = sum(words)
# columns = sum(number:2)

cars      BMWVolvoTeslaFordFerrariFordBMW
counts                                 40
dtype: object

In [52]:
df.min()

cars      BMW
counts      2
dtype: object

In [51]:
df.max()

cars      Volvo
counts        9
dtype: object

In [58]:
df.median(numeric_only=True)

counts    6.0
dtype: float64

In [60]:
df.count()
# filtering = null
# null qaytarmaydigan malunotni qidiradi
# bizni malumotimiz muammosiz

cars      7
counts    7
dtype: int64

In [61]:
df.std(numeric_only=True)
# standard deviation

counts    2.56348
dtype: float64

In [63]:
data_with_missing = {
    "cars": ["Ferrari", "BMD", None, "Tesla", None, "BWD"],
    "counts": [2, 4, None, 7, 4, None]
}

df_missing = pd.DataFrame(data_with_missing)
print(df_missing)

      cars  counts
0  Ferrari     2.0
1      BMD     4.0
2     None     NaN
3    Tesla     7.0
4     None     4.0
5      BWD     NaN

In [65]:
df_missing.isnull()

    cars  counts
0  False   False
1  False   False
2   True    True
3  False   False
4   True   False
5  False    True

In [66]:
df_missing.isnull().sum()
# gives how many nonvaluables in each column

cars      2
counts    2
dtype: int64

In [67]:
df_missing.dropna()
# deletes all = missing values

      cars  counts
0  Ferrari     2.0
1      BMD     4.0
3    Tesla     7.0

In [68]:
df_missing.dropna(how="all")
# first colum has nunevaluable? => delete

      cars  counts
0  Ferrari     2.0
1      BMD     4.0
3    Tesla     7.0
4     None     4.0
5      BWD     NaN

In [69]:
df_missing.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5]

In [73]:
df_missing.dropna(subset=["counts"])
# count qiymatiga asoslanadi

      cars  counts
0  Ferrari     2.0
1      BMD     4.0
3    Tesla     7.0
4     None     4.0

In [72]:
df_missing.dropna(subset=["cars"])
# cars qiymatiga asoslanadi

      cars  counts
0  Ferrari     2.0
1      BMD     4.0
3    Tesla     7.0
5      BWD     NaN

In [75]:
df_missing.fillna(0)
# missing qismga belgilangan narsani qoyib toldiradi

      cars  counts
0  Ferrari     2.0
1      BMD     4.0
2        0     0.0
3    Tesla     7.0
4        0     4.0
5      BWD     0.0

In [76]:
df_missing.fillna("unknown")

      cars   counts
0  Ferrari      2.0
1      BMD      4.0
2  unknown  unknown
3    Tesla      7.0
4  unknown      4.0
5      BWD  unknown

In [78]:
df_missing.fillna("<-->")

      cars counts
0  Ferrari    2.0
1      BMD    4.0
2     <-->   <-->
3    Tesla    7.0
4     <-->    4.0
5      BWD   <-->

In [79]:
df_missing.fillna({"cars":"unknown", "counts": "0"})

      cars counts
0  Ferrari    2.0
1      BMD    4.0
2  unknown      0
3    Tesla    7.0
4  unknown    4.0
5      BWD      0

In [87]:
df = pd.read_csv("Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [91]:
df.head(6)
# df.tail()
# df.tail(10)
# ========= ======== ========
# df = pd.read_excel("Titanic-Dataset.xlsx")
# df = pd.read_json("Titanic-Dataset.json")
# ========= ======== ========

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

In [96]:
# df dagi csv fileni excel filega ozgartirib export qildik
df.to_excel("test.xlsx")

In [95]:
testDF = pd.read_excel("test.xlsx")
testDF.head()

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [99]:
# Series => 1D
# Qoshimcha sifatida organdik => for only 1D version
cars = pd.Series(["BWD", "Tesla", "KIA"])
print(cars)

0      BWD
1    Tesla
2      KIA
dtype: object

In [98]:
cars_series = data_with_missing["cars"]
print(cars_series)

['Ferrari', 'BMD', None, 'Tesla', None, 'BWD']